---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-postgres
  template:
    metadata:
      labels:
        app: spring-boot-postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "example"

        vault.hashicorp.com/secret-volume-path-application-properties: "/deployments/config"
        vault.hashicorp.com/agent-inject-secret-application-properties: "secret/data/myapp/config"
        vault.hashicorp.com/agent-inject-template-application-properties: |-
          {{- with secret "secret/myapp/config" -}}
          spring.datasource.url=jdbc:postgresql://postgresql:5432/testdb
          spring.datasource.username={{ .Data.data.username }}
          spring.datasource.password={{ .Data.data.password }}
          spring.jpa.hibernate.ddl-auto=create
          {{- end }}
    spec:
      containers:
        - name: main
          image: quay.io/adewey/spring-boot-postgres
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
      serviceAccountName: vault-auth
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-postgres
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-postgres
  type: NodePort