---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-postgres
  template:
    metadata:
      labels:
        app: spring-boot-postgres
    spec:
      containers:
        - name: main
          image: quay.io/adewey/spring-boot-postgres
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-postgres
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-postgres
  type: NodePort